version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - epub
  - pdf

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - furo
    - sphinx
    - sphinx-autoapi
    - sphinx-copybutton
    - sphinx-inline-tabs
