codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: 70%
    patch: false

github_checks:
  annotations: false

ignore:
  - tests
  - docs
  - "src/pyg4ometry/pycgal_old"
  - "src/pyg4ometry/freecad"
  - "src/pyg4ometry/bdsim"
  - "src/pyg4ometry/gui"
